
CREATE SEQUENCE IF NOT EXISTS EMPLOYEE_SEQUENCE START WITH 1 increment by 1;

CREATE TABLE IF NOT EXISTS EMPLOYEE(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(255)
);

CREATE SEQUENCE IF NOT EXISTS DEPARTMENT_SEQUENCE START WITH 1 increment by 1;

CREATE TABLE IF NOT EXISTS DEPARTMENT(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(255),
READ_ONLY BOOLEAN,
MANDATORY BOOLEAN
);


CREATE TABLE IF NOT EXISTS MAP_EMPLOYEE_DEPARTMENT(
EMPLOYEE_ID INTEGER,
DEPARTMENT_ID INTEGER,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID),
PRIMARY KEY (EMPLOYEE_ID, DEPARTMENT_ID)
);

